### ISSUE TITLE
点击资源的时候出现拒绝访问

### ISSUE THREAD

**Issue by Mrwaite** [xiyouant/xiyouant.github.io#2]
拒绝访问

本缓存服务器管理员：wssupport@chinanetcenter.com

Via:jiangtaizhou63:9 (Cdn Cache Server V2.0)
## Generated Sun, 13 Dec 2015 07:23:15 GMT by cache.51cdn.com (Cdn Cache Server V2.0)

上面是点击之后出现的

是因为最近在添加其他的书吗

**Comment by leozhang2018** [comment]
由于开放访问，导致 CDN 流量过大。
费用支出太高，采用了访问白名单，只有特定域名的访问开源才可以正常访问。
目前还没有更好的方案，准备迁移至内网。

**Comment by magichan** [comment]
等待信息中心搭建好云平台，我们可以使用他作为资源服务器了
